[build]
  publish = "build"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self'; 
      script-src 'self' 'unsafe-inline' 'unsafe-eval' 
                 https://checkout.wompi.co 
                 https://api.wompi.co
                 https://*.wompi.co
                 https://connect.facebook.net; 
      connect-src 'self' 
                  https://api.wompi.co 
                  https://checkout.wompi.co
                  https://*.wompi.co 
                  https://supercasa-backend-vvu1.onrender.com
                  https://www.facebook.com; 
      img-src 'self' data: 
              https://*.wompi.co 
              https://wompi.com
              https://*.facebook.com
              https://*.fbcdn.net
              https://www.infobae.com
              https://images.unsplash.com
              https://*.googleusercontent.com
              https://www.google.com; 
      style-src 'self' 'unsafe-inline' 
                https://*.wompi.co; 
      font-src 'self' data: 
               https://*.wompi.co; 
      frame-src 'self' 
                https://checkout.wompi.co 
                https://*.wompi.co;
      object-src 'none';
      base-uri 'self';
      form-action 'self' https://*.wompi.co;
    """
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200