# netlify.toml - Configuración para resolver problemas de CSP/CORS con WOMPI

[build]
  publish = "build"
  command = "npm run build"

# Headers optimizados para WOMPI
[[headers]]
  for = "/*"
  [headers.values]
    # Content Security Policy optimizada para WOMPI
    Content-Security-Policy = """
      default-src 'self'; 
      script-src 'self' 'unsafe-inline' 'unsafe-eval' 
                 https://checkout.wompi.co 
                 https://api.wompi.co
                 https://*.wompi.co; 
      connect-src 'self' 
                  https://api.wompi.co 
                  https://production.wompi.co
                  https://checkout.wompi.co
                  https://*.wompi.co 
                  https://supercasa-backend-vvu1.onrender.com; 
      img-src 'self' data: 
              https://*.wompi.co 
              https://wompi.com; 
      style-src 'self' 'unsafe-inline' 
                https://*.wompi.co; 
      font-src 'self' data: 
               https://*.wompi.co; 
      frame-src 'self' 
                https://checkout.wompi.co 
                https://*.wompi.co;
      object-src 'none';
      base-uri 'self';
      form-action 'self' https://*.wompi.co;
    """
    
    # CORS Headers para API calls
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    
    # Security Headers adicionales
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirects para SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200